[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.25.2"
edition = "2021"
rust-version = "1.88"
authors = ["Alloy Contributors"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/alloy-rs/alloy-evm"
repository = "https://github.com/alloy-rs/alloy-evm"
exclude = ["benches/", "tests/"]

[workspace.lints.rustdoc]
all = "warn"

[workspace.lints.rust]
missing-debug-implementations = "warn"
missing-docs = "warn"
unreachable-pub = "warn"
unused-must-use = "deny"
rust-2018-idioms = "deny"
unnameable-types = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
missing-const-for-fn = "warn"
use-self = "warn"
option-if-let-else = "allow"
redundant-clone = "warn"

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace.dependencies]
alloy-evm = { version = "0.25.2", path = "crates/evm", default-features = false }
alloy-op-evm = { version = "0.25.2", path = "crates/op-evm", default-features = false }

# alloy
alloy-eip2124 = { version = "0.2", default-features = false }
alloy-chains = { version = "0.2.0", default-features = false }
alloy-eips = { version = "1.0.34", default-features = false }
alloy-consensus = { version = "1.1.2", default-features = false }
alloy-primitives = { version = "1.0.0", default-features = false }
alloy-sol-types = { version = "1.0.0", default-features = false }
alloy-hardforks = { version = "0.4.2" }
alloy-rpc-types-eth = { version = "1.1.2", default-features = false }
alloy-rpc-types-engine = { version = "1.1.2", default-features = false }

# op-alloy
alloy-op-hardforks = { version = "0.4.2" }
op-alloy = { git = "https://github.com/mantle-xyz/op-alloy", tag = "v2.2.0", default-features = false, features = [
    "consensus",
] }

# revm
revm = { git = "https://github.com/mantle-xyz/revm", branch = "fix/op-revm-bvm-eth-deposit-cold-reset", default-features = false }
op-revm = { git = "https://github.com/mantle-xyz/revm", branch = "fix/op-revm-bvm-eth-deposit-cold-reset", default-features = false }

# misc
auto_impl = "1"
derive_more = { version = "2", default-features = false, features = ["full"] }
serde = { version = "1", default-features = false, features = ["derive"] }
thiserror = { version = "2.0.0", default-features = false }
serde_json = "1"
test-case = "3"

# [patch."https://github.com/mantle-xyz/revm"]
# revm = { path = "../revm/crates/revm" }
# revm-bytecode = { path = "../revm/crates/bytecode" }
# revm-state = { path = "../revm/crates/state" }
# revm-primitives = { path = "../revm/crates/primitives" }
# revm-interpreter = { path = "../revm/crates/interpreter" }
# revm-inspector = { path = "../revm/crates/inspector" }
# revm-context = { path = "../revm/crates/context" }
# revm-context-interface = { path = "../revm/crates/context/interface" }
# revm-database = { path = "../revm/crates/database" }
# revm-database-interface = { path = "../revm/crates/database/interface" }
# op-revm = { path = "../revm/crates/op-revm" }

# [patch."https://github.com/mantle-xyz/op-alloy"]
# op-alloy = { path = "../op-alloy/crates/op-alloy" }
# op-alloy-consensus = { path = "../op-alloy/crates/consensus" }
